services:
  db:
    container_name: db
    build: docker/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/db_init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=superman
      - POSTGRES_USER=root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 2s
      retries: 5
  migrate:
    image: migrate/migrate
    volumes:
      - ./db/migrations:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://root:superman@db:5432/api?sslmode=disable",
        "up",
      ]
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
  api:
    container_name: api
    build:
      dockerfile: docker/api/Dockerfile
      context: .
    depends_on:
      - migrate
    ports:
      - "9001:9001"
    environment:
      - CONFIG_FILE=/usr/configs/local/config.json
      - VERSION=local

volumes:
  postgres_data:
