-- script ran to initialize the db

CREATE DATABASE api WITH CONNECTION LIMIT 200;
CREATE USER api_user WITH PASSWORD 'api_user';

GRANT CONNECT ON DATABASE api TO api_user;
GRANT USAGE ON SCHEMA public TO api_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO api_user;
ALTER DEFAULT PRIVILEGES FOR ROLE api_user IN SCHEMA public GRANT ALL ON TABLES TO api_user;
